name = input('Введите ФИО студента: ')
groop = input('Введите группу студента: ')
math = input('Введите оценку по математике: ')
histor = input('Введите оценку по истории: ')
fiz = input('Введите оценку по физике: ')

print(f'Профиль студента:')
print(f'ФИО: {name}')
print(f'Группа: {groop}')
print(f'Оценки:')
print(f'Математика: {math}')
print(f'История: {histor}')
print(f'Физика: {fiz}')
